from __future__ import annotations

import hashlib
import json
import platform
import sys
import traceback
import zipfile
from dataclasses import asdict, dataclass
from datetime import UTC, datetime
from pathlib import Path

from .parser import PdfTextExtractor


@dataclass(slots=True)
class DiagnosticManifest:
    generated_at_utc: str
    application_version: str
    python_version: str
    platform: str
    source_filename: str
    source_size_bytes: int
    source_sha256: str
    include_original_pdf: bool
    extraction_status: str
    extraction_error: str
    processing_error: str


class ParserDiagnosticsExporter:
    """Create a privacy-conscious ZIP package for unsupported or malformed PDFs."""

    def __init__(self, application_version: str = "0.9.0-beta") -> None:
        self.application_version = application_version
        self.extractor = PdfTextExtractor()

    def export(
        self,
        source: Path,
        destination: Path,
        error: BaseException | str,
        *,
        include_original_pdf: bool = False,
    ) -> Path:
        source = Path(source)
        destination = Path(destination)
        destination.parent.mkdir(parents=True, exist_ok=True)

        extraction_status = "not-attempted"
        extraction_error = ""
        pages: list[str] = []
        try:
            extracted = self.extractor.extract(source)
            pages = extracted.pages
            extraction_status = "success"
        except Exception as exc:  # diagnostics must never mask the original error
            extraction_status = "failed"
            extraction_error = f"{type(exc).__name__}: {exc}"

        processing_error = (
            "".join(traceback.format_exception(error))
            if isinstance(error, BaseException)
            else str(error)
        )
        digest = self._sha256(source) if source.exists() else ""
        manifest = DiagnosticManifest(
            generated_at_utc=datetime.now(UTC).isoformat(),
            application_version=self.application_version,
            python_version=sys.version,
            platform=platform.platform(),
            source_filename=source.name,
            source_size_bytes=source.stat().st_size if source.exists() else 0,
            source_sha256=digest,
            include_original_pdf=include_original_pdf,
            extraction_status=extraction_status,
            extraction_error=extraction_error,
            processing_error=processing_error,
        )

        with zipfile.ZipFile(destination, "w", compression=zipfile.ZIP_DEFLATED) as archive:
            archive.writestr("manifest.json", json.dumps(asdict(manifest), indent=2))
            archive.writestr("processing_error.txt", processing_error)
            archive.writestr(
                "extracted_text.txt",
                "\n\n".join(f"===== PAGE {index} =====\n{text}" for index, text in enumerate(pages, 1)),
            )
            archive.writestr(
                "README.txt",
                "Parser diagnostics generated by Interest Statement Generator Pro.\n"
                "Review extracted_text.txt for confidential information before sharing.\n"
                "The original PDF is excluded unless explicitly requested.\n",
            )
            if include_original_pdf and source.exists():
                archive.write(source, arcname=f"original/{source.name}")
        return destination

    @staticmethod
    def _sha256(path: Path) -> str:
        digest = hashlib.sha256()
        with path.open("rb") as handle:
            for chunk in iter(lambda: handle.read(1024 * 1024), b""):
                digest.update(chunk)
        return digest.hexdigest()
